spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issue
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true